### ISSUE TITLE
Help needed for using udp server

### ISSUE THREAD

**Issue by Razbotics** [alduxvm/DronePilot#5]
Hey nice work i tested your udp server to send imu data from multiwii to my pc using rpi also tried the other way by sending RC commands and it works great but i need some help developing a python script that can receive imu data from rpi and send RC commands from my pc parallely. Also a script in rpi side that sends imu data and receives rc data to control the flight controller... is this possible...Also i want to know why you used twisted internet...can udp server be implemented just by using socket and threading modules? I dont know about twisted internet module as it is hard to find tutorials on it...

**Comment by alduxvm** [comment]
hi, yes, you can refer to my original multiwii repository https://github.com/alduxvm/pymultiwii that this repository uses, in there in the issues section you can see that a lot of people is having problems because the new firmwares kinda not support that function or they change the order of the channels. I recommend to make the tests first with the pymultwii repository and then start debugging this one.

twisted is much easier to use that having to build the server and client using socket and threading modules, and its actually faster. 
 
you can implement udp or another transport method to get the information to the system, everything depends on what you're trying to achieve. If you want more help you can send me an email to aldo@altax.net and I can help you in the overall architecture of what youre trying to achieve.
